### ISSUE TITLE
[MULTIPLAYER]: creation of a multiplayer lobby

### ISSUE THREAD

**Issue by Ewen02** [aureliancnx/R-Type#112]

**Comment by aureliancnx** [comment]
Packets are ready to be used. We need to implement the GUI.

**Comment by aureliancnx** [comment]
In the roadmap, implementation in progress (assigned to @DosserPaul)
https://github.com/aureliancnx/R-Type/tree/feature/lobby

**Comment by aureliancnx** [comment]
https://github.com/aureliancnx/R-Type/pull/228

**Comment by DosserPaul** [comment]
#249
